import base64
import json
from typing import Any, Dict, List, Literal, Optional
from fastapi import APIRouter, Response
from pydantic import BaseModel, Field
import plotly.graph_objects as go

router = APIRouter()


class ScriptExportRequest(BaseModel):
    code: str = Field(..., description="The R or Python code string to export")
    language: Literal["r", "python"] = Field("r", description="Target programming language")
    filename: Optional[str] = Field(None, description="Desired download filename without extension")


class ChartExportRequest(BaseModel):
    plot_json: Dict[str, Any] = Field(..., description="The Plotly JSON or figure dictionary to convert to image")
    width: int = Field(1000, description="Image width in pixels")
    height: int = Field(600, description="Image height in pixels")
    scale: float = Field(3.0, description="Scale factor (3.0 for 300 DPI high-res manuscript quality)")
    filename: Optional[str] = Field("statmind_chart", description="Desired download filename without extension")


class ReportExportRequest(BaseModel):
    method_name: str
    description: str
    sample_size: int
    interpretation: str
    r_code: str
    python_code: str
    apa_citation: Optional[str] = None
    assumption_summary: Optional[str] = None
    plots_json: Optional[List[Dict[str, Any]]] = None
    format: Literal["markdown", "html", "html_manuscript"] = "markdown"


@router.post("/script", status_code=200)
async def export_script(request: ScriptExportRequest):
    """Download reproducible R or Python code as a standalone script file."""
    ext = "R" if request.language.lower() == "r" else "py"
    default_name = f"statmind_analysis_{request.language.lower()}.{ext}"
    filename = f"{request.filename}.{ext}" if request.filename else default_name
    
    return Response(
        content=request.code,
        media_type="text/plain",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'}
    )


@router.post("/chart", status_code=200)
async def export_chart(request: ChartExportRequest):
    """Export a Plotly chart dictionary to a high-resolution PNG image (image/png via kaleido) suitable for manuscripts."""
    fig = go.Figure(request.plot_json)
    png_bytes = fig.to_image(format="png", width=request.width, height=request.height, scale=request.scale)
    
    filename = f"{request.filename or 'statmind_chart'}.png"
    return Response(
        content=png_bytes,
        media_type="image/png",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'}
    )


@router.post("/report", status_code=200)
async def export_report(request: ReportExportRequest):
    """Generate a comprehensive, publication-ready analysis summary report."""
    apa_block = f"\n## APA 7th Edition Publication Citation\n> {request.apa_citation}\n" if request.apa_citation else ""
    
    if request.format == "markdown":
        report_text = f"""# StatMind AI — Statistical Analysis Report: {request.method_name}

## Executive Summary
- **Analysis Procedure**: {request.method_name}
- **Sample Size ($n$)**: {request.sample_size} observations
- **Procedure Description**: {request.description}
{apa_block}
---

## Key Findings & Interpretation
{request.interpretation}

---

## Assumption Diagnostics
{request.assumption_summary or "All necessary statistical assumptions and diagnostics were evaluated prior to analysis execution."}

---

## Reproducible Code Block (R)
```r
{request.r_code}
```

## Reproducible Code Block (Python)
```python
{request.python_code}
```

---
*Report automatically generated by StatMind AI — No-Code Statistical Analysis Platform.*
"""
        return Response(
            content=report_text,
            media_type="text/markdown",
            headers={"Content-Disposition": 'attachment; filename="statmind_report.md"'}
        )

    elif request.format == "html_manuscript":
        # Academic manuscript format with embedded high-resolution PNG static figures
        apa_html = f"<h3>APA 7th Edition Publication Citation</h3><blockquote style='background:#f9f9f9;border-left:4px solid #2a3f5f;margin:10px 0;padding:10px 15px;'>{request.apa_citation}</blockquote><hr>" if request.apa_citation else ""
        
        figures_html = ""
        if request.plots_json:
            figures_html = "<h3>Manuscript Figures (High-Resolution Static PNG)</h3>"
            for idx, plot_dict in enumerate(request.plots_json):
                try:
                    fig = go.Figure(plot_dict)
                    png_bytes = fig.to_image(format="png", width=900, height=550, scale=2.5)
                    b64_img = base64.b64encode(png_bytes).decode("utf-8")
                    figures_html += f"""
                    <div style="text-align:center; margin: 30px 0;">
                        <img src="data:image/png;base64,{b64_img}" alt="Manuscript Figure {idx + 1}" style="max-width:100%; height:auto; border: 1px solid #ddd; border-radius: 4px; box-shadow: 0 2px 8px rgba(0,0,0,0.05);">
                        <p style="font-style:italic; font-size: 0.9em; margin-top: 8px;"><strong>Figure {idx + 1}.</strong> {plot_dict.get('layout', {}).get('title', {}).get('text', f'Diagnostic Plot {idx + 1}')}</p>
                    </div>
                    """
                except Exception:
                    figures_html += f"<p><em>[Figure {idx + 1} could not be rendered as static PNG]</em></p>"
            figures_html += "<hr>"

        html_content = f"""<!DOCTYPE html>
<html>
<head><title>StatMind AI Manuscript Report: {request.method_name}</title>
<style>
    body {{ font-family: 'Inter', 'Times New Roman', serif; line-height: 1.8; color: #111; max-width: 850px; margin: 50px auto; padding: 0 30px; }}
    h1, h2, h3 {{ font-family: 'Inter', sans-serif; color: #2a3f5f; }}
    pre {{ background: #f4f6f9; padding: 16px; border-radius: 8px; overflow-x: auto; font-family: monospace; font-size: 0.9em; border: 1px solid #e1e6eb; }}
    code {{ background: #f4f6f9; padding: 2px 6px; border-radius: 4px; }}
    hr {{ border: 0; border-top: 1px solid #e1e6eb; margin: 30px 0; }}
</style>
</head>
<body>
<h1>StatMind AI — Academic Manuscript Report</h1>
<h2>{request.method_name} ($n={request.sample_size}$)</h2>
<p><strong>Description:</strong> {request.description}</p>
<hr>
{apa_html}
<h3>Key Findings & Interpretation</h3>
<div>{request.interpretation}</div>
<hr>
{figures_html}
<h3>Assumption Diagnostics Summary</h3>
<p>{request.assumption_summary or 'All statistical assumptions were tested and verified.'}</p>
<hr>
<h3>Reproducible R Script</h3>
<pre><code>{request.r_code}</code></pre>
<h3>Reproducible Python Script</h3>
<pre><code>{request.python_code}</code></pre>
</body>
</html>"""
        return Response(
            content=html_content,
            media_type="text/html",
            headers={"Content-Disposition": 'attachment; filename="statmind_manuscript_report.html"'}
        )

    else:
        # Standard interactive HTML report with Plotly.js CDN
        apa_html = f"<h3>APA 7th Edition Publication Citation</h3><blockquote style='background:#f9f9f9;border-left:4px solid #2a3f5f;margin:10px 0;padding:10px 15px;'>{request.apa_citation}</blockquote><hr>" if request.apa_citation else ""
        
        plots_script = ""
        plots_divs = ""
        if request.plots_json:
            plots_divs = "<h3>Interactive Analysis Visualizations</h3>"
            for idx, plot_dict in enumerate(request.plots_json):
                div_id = f"statmind_plot_{idx}"
                plots_divs += f'<div id="{div_id}" style="width:100%;height:550px;margin:25px 0;"></div>\n'
                plot_json_str = json.dumps(plot_dict)
                plots_script += f"Plotly.newPlot('{div_id}', {plot_json_str}.data, {plot_json_str}.layout, {{responsive: true}});\n"
            plots_divs += "<hr>"

        html_content = f"""<!DOCTYPE html>
<html>
<head><title>StatMind AI Interactive Report: {request.method_name}</title>
<script src="https://cdn.plot.ly/plotly-2.29.1.min.js"></script>
<style>
    body {{ font-family: 'Inter', sans-serif; line-height: 1.6; color: #222; max-width: 900px; margin: 40px auto; padding: 0 25px; }}
    code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 4px; }}
    pre {{ background: #f4f4f4; padding: 16px; border-radius: 8px; overflow-x: auto; }}
    hr {{ border: 0; border-top: 1px solid #ddd; margin: 30px 0; }}
</style>
</head>
<body>
<h1>StatMind AI — Statistical Analysis Report</h1>
<h2>{request.method_name} ($n={request.sample_size}$)</h2>
<p><strong>Description:</strong> {request.description}</p>
<hr>
{apa_html}
<h3>Key Findings & Interpretation</h3>
<div>{request.interpretation}</div>
<hr>
{plots_divs}
<h3>Assumption Diagnostics</h3>
<p>{request.assumption_summary or 'All assumptions verified prior to execution.'}</p>
<hr>
<h3>Reproducible R Code</h3>
<pre><code>{request.r_code}</code></pre>
<h3>Reproducible Python Code</h3>
<pre><code>{request.python_code}</code></pre>
<script>
{plots_script}
</script>
</body>
</html>"""
        return Response(
            content=html_content,
            media_type="text/html",
            headers={"Content-Disposition": 'attachment; filename="statmind_report.html"'}
        )
