from datetime import datetime
from jinja2 import Environment, FileSystemLoader
import os
from typing import Any, Dict, Optional


class CodeGenerator:
    """Jinja2-based R and Python code template renderer for transparent educational display."""
    
    _env: Optional[Environment] = None

    @classmethod
    def get_environment(cls) -> Environment:
        if cls._env is None:
            # Locate r_templates directory relative to workspace or app
            base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../../r_templates"))
            if not os.path.exists(base_dir):
                # Fallback check
                base_dir = os.path.abspath("r_templates")
            cls._env = Environment(
                loader=FileSystemLoader(base_dir),
                trim_blocks=True,
                lstrip_blocks=True
            )
        return cls._env

    @classmethod
    def render_r_template(cls, template_name: str, context: Dict[str, Any]) -> str:
        """Render an R code template using context dictionary."""
        env = cls.get_environment()
        template = env.get_template(template_name)
        
        # Add default timestamp if not present
        if "timestamp" not in context:
            context["timestamp"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        if "dataset_name" not in context:
            context["dataset_name"] = "user_dataset"
            
        return template.render(**context)

    @classmethod
    def format_python_code(cls, method_name: str, code_body: str, dataset_name: str = "user_dataset") -> str:
        """Format Python code block with standard educational header."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        header = f"""# ================================================================
# {method_name} Analysis
# Generated by StatMind AI
# Dataset: {dataset_name}
# Date: {timestamp}
# ================================================================

"""
        return header + code_body.strip()
