from datetime import datetime
from jinja2 import Environment, FileSystemLoader
import os
from typing import Any, Dict, Optional


class CodeGenerator:
    """Jinja2-based R and Python code template renderer for transparent educational display."""
    
    _env: Optional[Environment] = None

    @classmethod
    def get_environment(cls) -> Environment:
        if cls._env is None:
            # Locate r_templates directory relative to workspace, app, or cwd
            candidate_paths = [
                os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../../r_templates")),
                os.path.abspath("r_templates"),
                os.path.join(os.getcwd(), "r_templates"),
                "/app/r_templates"
            ]
            valid_paths = [p for p in candidate_paths if os.path.exists(p)]
            if not valid_paths:
                valid_paths = [candidate_paths[0]]
            cls._env = Environment(
                loader=FileSystemLoader(valid_paths),
                trim_blocks=True,
                lstrip_blocks=True
            )
        return cls._env

    @classmethod
    def render_r_template(cls, template_name: str, context: Dict[str, Any]) -> str:
        """Render an R code template using context dictionary."""
        try:
            env = cls.get_environment()
            template = env.get_template(template_name)
            
            # Add default timestamp if not present
            if "timestamp" not in context:
                context["timestamp"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            if "dataset_name" not in context:
                context["dataset_name"] = "user_dataset"
                
            rendered = template.render(**context)
            
            # Inject universal Data Importation guide right after the initial comment header
            import_guide = """# ==============================================================================
# 1. DATA IMPORTATION (IMPORTANT: Paste your exact dataset file path below)
# ==============================================================================
# To execute this script in R or RStudio on your computer, paste the exact
# file path to your CSV or Excel dataset inside read.csv() below:
# (e.g., "C:/Users/name/Documents/survey_data.csv" or "data/project_file.xlsx")
#
# data <- read.csv("path/to/your_dataset.csv", stringsAsFactors = FALSE)
# =============================================================================="""

            parts = rendered.split('\n\n', 1)
            if len(parts) == 2:
                return parts[0] + "\n\n" + import_guide + "\n\n" + parts[1]
            return import_guide + "\n\n" + rendered
        except Exception as e:
            return f"""# ================================================================
# {template_name.replace('.R.j2', '')} R Code
# Generated by Quantigen AI (Fallback Mode)
# ================================================================

# ==============================================================================
# 1. DATA IMPORTATION (IMPORTANT: Paste your exact dataset file path below)
# ==============================================================================
# data <- read.csv("path/to/your_dataset.csv", stringsAsFactors = FALSE)
# ==============================================================================

# Note: R template '{template_name}' could not be loaded ({str(e)}).
# Basic R execution pattern for this method:
library(tidyverse)
# Please check your variables and run the standard procedure in R console.
"""

    @classmethod
    def format_python_code(cls, method_name: str, code_body: str, dataset_name: str = "user_dataset") -> str:
        """Format Python code block with standard educational header and data importation guide."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        header = f"""# ==============================================================================
# {method_name} Analysis
# Generated by Quantigen AI — Next-Gen Quantitative Statistical Platform
# Dataset: {dataset_name}
# Date: {timestamp}
# ==============================================================================

# ==============================================================================
# 1. DATA IMPORTATION (IMPORTANT: Paste your exact dataset file path below)
# ==============================================================================
# To execute this script locally on your computer, Jupyter Notebook, or server:
# Replace "your_dataset.csv" below with the exact file path to your dataset
# (e.g., "C:/Users/name/Documents/survey_data.csv" or "data/project_file.xlsx")
#
# import pandas as pd
# data = pd.read_csv("path/to/your_dataset.csv")
# ==============================================================================

"""
        return header + code_body.strip()
